
disqus:
  comments: false
  disqus_shortname: 'millennial-3'
  
google-ID: 'UA-112060364-2'

menu:
- {name: 'Thoughts and Feelings',  url: 'blog'}
- {name: 'Portfolio', url: 'folio'}
- {name: 'Some Cool Shit',       url: 'tybg'}
- {name: 'Training',      url: 'stayhard'}
- {name: 'About',              url: 'yearningsohardimadeawebsite'}
- {name: 'Contact',            url: 'contact'}

social:
- {icon: 'twitter', link:    'https://bsky.app/profile/gokusippinlean.bsky.social'}
- {icon: 'youtube', link:   'http://www.youtube.com/@unclerico2140'}
- {icon: 'instagram', link:  'https://instagram.com/coachpsa'}
- {icon: 'envelope', link:   'mailto:a3.ponce@gmail.com'}
- {icon: 'heart', link: 'https://www.youtube.com/watch?v=oqj8EJQTyBI'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Check out my other bullshit!'

post_date_prefix: 'Written on'
